### ISSUE TITLE
is it possible to use height in %?

### ISSUE THREAD

**Issue by luisrudge** [flot/flot#1339]
I want to do something like this:

``` css
    #chart {
      width: 100%;
      min-height: 200px;
      height: auto;
    }
```
