### ISSUE TITLE
It's possible put my area chart on vertical?

### ISSUE THREAD

**Issue by pedropcruz** [flot/flot#1456]
Hello guys,

It's possible put this:

![screenshot_1](https://cloud.githubusercontent.com/assets/6757946/8986610/d8837d2a-36d4-11e5-8d8c-3df38304bb42.png)

on this:

http://prntscr.com/7yusfb 

?

Thanks.

**Comment by 153957** [comment]
```css
#graph {
    -ms-transform: rotate(90deg); /* IE 9 */
    -webkit-transform: rotate(90deg); /* Chrome, Safari, Opera */
    transform: rotate(90deg);
}
```
